"""empty message

Revision ID: 1e5d6d22ec26
Revises: 4460fd33d982
Create Date: 2014-11-28 17:38:41.267314

"""

# revision identifiers, used by Alembic.
revision = '1e5d6d22ec26'
down_revision = '4460fd33d982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
