"""empty message

Revision ID: 29250aebe818
Revises: f5526e304cb
Create Date: 2014-11-16 15:14:32.143326

"""

# revision identifiers, used by Alembic.
revision = '29250aebe818'
down_revision = 'f5526e304cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
