"""empty message

Revision ID: 3fa20ea9b8e9
Revises: 29250aebe818
Create Date: 2014-11-16 17:09:56.397945

"""

# revision identifiers, used by Alembic.
revision = '3fa20ea9b8e9'
down_revision = '29250aebe818'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
