"""empty message

Revision ID: 434b89278acd
Revises: 3fa20ea9b8e9
Create Date: 2014-11-16 17:17:33.861467

"""

# revision identifiers, used by Alembic.
revision = '434b89278acd'
down_revision = '3fa20ea9b8e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_avatar')
    ### end Alembic commands ###
