"""empty message

Revision ID: 4460fd33d982
Revises: 434b89278acd
Create Date: 2014-11-28 17:20:44.526494

"""

# revision identifiers, used by Alembic.
revision = '4460fd33d982'
down_revision = '434b89278acd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
