"""empty message

Revision ID: f5526e304cb
Revises: 51f5ccfba190
Create Date: 2014-11-12 19:45:45.182745

"""

# revision identifiers, used by Alembic.
revision = 'f5526e304cb'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
